"""add budget type and description

Revision ID: 16b49bcaf865
Revises: f3fcfe68391c
Create Date: 2026-05-03 20:54:17.968776

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '16b49bcaf865'
down_revision: Union[str, None] = 'f3fcfe68391c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('type', sa.Enum('income', 'expense', name='budgettype'), nullable=False))
    op.add_column('budgets', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('budgets', 'description')
    op.drop_column('budgets', 'type')
    # ### end Alembic commands ###
