"""add type and description to categories table

Revision ID: b97d04cabaeb
Revises: 16b49bcaf865
Create Date: 2026-05-03 21:35:33.244492

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b97d04cabaeb'
down_revision: Union[str, None] = '16b49bcaf865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
