"""add budget_id to transactions

Revision ID: e8a5f110b15c
Revises: b97d04cabaeb
Create Date: 2026-05-03 22:21:20.016650

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e8a5f110b15c'
down_revision: Union[str, None] = 'b97d04cabaeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('budget_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'budgets', ['budget_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'budget_id')
    # ### end Alembic commands ###
