"""unique_constraint_category_user_name

Revision ID: f3493f80ea8c
Revises: 57e25e795a25
Create Date: 2026-05-03 19:23:52.650687

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f3493f80ea8c'
down_revision: Union[str, None] = '57e25e795a25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_categories_user_name', 'categories', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_categories_user_name', 'categories', type_='unique')
    # ### end Alembic commands ###
