"""soft delete and idempotency key on transactions

Revision ID: f9b822308896
Revises: 23b4e9c78989
Create Date: 2026-04-26 01:44:16.231008

"""
from __future__ import annotations
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f9b822308896'
down_revision: Union[str, None] = '23b4e9c78989'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('idempotency_key', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_transactions_user_idempotency', 'transactions', ['user_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transactions_user_idempotency', 'transactions', type_='unique')
    op.drop_column('transactions', 'deleted_at')
    op.drop_column('transactions', 'idempotency_key')
    # ### end Alembic commands ###
